-keep class android.** { *; }
-keep class android.**$Stub { *; }
-keep class com.google.** { *; }
-keep class dalvik.** { *; }
-keep class libcore.** { *; }
-keep class com.jni.** { *; }
-keep class com.rixiangtek.** { *; }

-dontwarn android.**
-dontwarn com.android.**
-dontwarn com.google.**
-dontwarn dalvik.**
-dontwarn libcore.**